SCHEMA = {
    "Study": [
        "NCTId",
        "OrgStudyId",
        "OrgFullName",
        "OrgClass",
        "BriefTitle",
        "OfficialTitle",
        "Acronym",
        "StatusVerifiedDate",
        "OverallStatus",
        "HasExpandedAccess",
        "StartDate",
        "PrimaryCompletionDate",
        "PrimaryCompletionDateType",
        "CompletionDate",
        "CompletionDateType",
        "StudyFirstSubmitDate",
        "StudyFirstSubmitQCDate",
        "StudyFirstPostDate",
        "StudyFirstPostDateType",
        "LastUpdateSubmitDate",
        "LastUpdatePostDate",
        "LastUpdatePostDateType",
        "ResponsiblePartyType",
        "LeadSponsorName",
        "LeadSponsorClass",
        "OversightHasDMC",
        "BriefSummary",
        "DetailedDescription",
        "Condition",
        "Keyword",
        "StudyType",
        "PatientRegistry",
        "DesignObservationalModel",
        "DesignTimePerspective",
        "EnrollmentCount",
        "EnrollmentType",
        "EligibilityCriteria",
        "HealthyVolunteers",
        "Sex",
        "MinimumAge",
        "MaximumAge",
        "StdAge",
        "StudyPopulation",
        "SamplingMethod",
        "VersionHolder",
        "HasResults",
        "StartDateType",
        "IsFDARegulatedDrug",
        "IsFDARegulatedDevice",
        "Phase",
        "DesignAllocation",
        "DesignInterventionModel",
        "DesignPrimaryPurpose",
        "DesignMasking",
        "DesignWhoMasked",
        "IPDSharing",
        "ResultsFirstSubmitDate",
        "ResultsFirstSubmitQCDate",
        "ResultsFirstPostDate",
        "ResultsFirstPostDateType",
        "EventsFrequencyThreshold",
        "AgreementPISponsorEmployee",
        "AgreementRestrictiveAgreement",
        "PointOfContactTitle",
        "PointOfContactOrganization",
        "PointOfContactEMail",
        "PointOfContactPhone",
        "ResponsiblePartyInvestigatorFullName",
        "ResponsiblePartyInvestigatorTitle",
        "ResponsiblePartyInvestigatorAffiliation",
        "ResponsiblePartyOldNameTitle",
        "ResponsiblePartyOldOrganization",
        "FlowPreAssignmentDetails",
        "EventsTimeFrame",
        "EventsDescription",
        "LimitationsAndCaveatsDescription",
        "AgreementRestrictionType",
        "AgreementOtherDetails",
        "LastKnownStatus",
        "BioSpecRetention",
        "BioSpecDescription",
        "GenderBased",
        "NCTIdAlias",
        "FlowRecruitmentDetails",
        "BaselinePopulationDescription",
        "IsUSExport",
        "WhyStopped",
        "DesignInterventionModelDescription",
        "IPDSharingDescription",
        "IsUnapprovedDevice",
        "PointOfContactPhoneExt",
        "DesignMaskingDescription",
        "GenderDescription",
        "TargetDuration",
        "OrgStudyIdType",
        "OrgStudyIdLink",
        "IPDSharingInfoType",
        "IPDSharingTimeFrame",
        "IPDSharingAccessCriteria",
        "DispFirstSubmitDate",
        "DispFirstSubmitQCDate",
        "DispFirstPostDate",
        "DispFirstPostDateType",
        "RemovedCountry",
        "UnpostedResponsibleParty",
        "EstimatedResultsFirstSubmitDate",
        "FirstMCPPostDate",
        "FirstMCPPostDateType",
        "IPDSharingURL",
        "DelayedPosting",
        "ExpandedAccessNCTId",
        "ExpandedAccessStatusForNCTId",
        "FlowTypeUnitsAnalyzed",
        "LargeDocNoSAP",
    ],
    "SecondaryIdInfos": [
        "NCTId",
        "SecondaryId",
        "SecondaryIdType",
        "SecondaryIdDomain",
    ],
    "ArmGroups": [
        "NCTId",
        "ArmGroupLabel",
        "ArmGroupType",
        "ArmGroupDescription",
        "ArmGroupInterventionName",
    ],
    "Collaborators": [
        "NCTId",
        "CollaboratorName",
        "CollaboratorClass",
    ],
    "Interventions": [
        "NCTId",
        "InterventionType",
        "InterventionName",
        "InterventionDescription",
        "InterventionArmGroupLabel",
        "InterventionOtherName",
    ],
    "PrimaryOutcomes": [
        "NCTId",
        "PrimaryOutcomeMeasure",
        "PrimaryOutcomeDescription",
        "PrimaryOutcomeTimeFrame",
    ],
    "SecondaryOutcomes": [
        "NCTId",
        "SecondaryOutcomeMeasure",
        "SecondaryOutcomeDescription",
        "SecondaryOutcomeTimeFrame",
    ],
    "OverallOfficials": [
        "NCTId",
        "OverallOfficialName",
        "OverallOfficialAffiliation",
        "OverallOfficialRole",
    ],
    "Locations": [
        "NCTId",
        "LocationFacility",
        "LocationCity",
        "LocationState",
        "LocationZip",
        "LocationCountry",
    ],
    "StudyReferences": [
        "NCTId",
        "ReferencePMID",
        "ReferenceType",
        "ReferenceCitation",
    ],
    "ConditionMeshes": [
        "NCTId",
        "ConditionMeshId",
        "ConditionMeshTerm",
    ],
    "InterventionMeshes": [
        "NCTId",
        "InterventionMeshId",
        "InterventionMeshTerm",
    ],
    "ConditionAncestors": [
        "NCTId",
        "ConditionAncestorId",
        "ConditionAncestorTerm",
    ],
    "InterventionAncestors": [
        "NCTId",
        "InterventionAncestorId",
        "InterventionAncestorTerm",
    ],
    "ConditionBrowseLeaves": [
        "NCTId",
        "ConditionBrowseLeafId",
        "ConditionBrowseLeafName",
        "ConditionBrowseLeafAsFound",
        "ConditionBrowseLeafRelevance",
    ],
    "InterventionBrowseLeaves": [
        "NCTId",
        "InterventionBrowseLeafId",
        "InterventionBrowseLeafName",
        "InterventionBrowseLeafAsFound",
        "InterventionBrowseLeafRelevance",
    ],
    "ConditionBrowseBranches": [
        "NCTId",
        "ConditionBrowseBranchAbbrev",
        "ConditionBrowseBranchName",
    ],
    "InterventionBrowseBranches": [
        "NCTId",
        "InterventionBrowseBranchAbbrev",
        "InterventionBrowseBranchName",
    ],
    "OtherOutcomes": [
        "NCTId",
        "OtherOutcomeMeasure",
        "OtherOutcomeDescription",
        "OtherOutcomeTimeFrame",
    ],
    "CentralContacts": [
        "NCTId",
        "CentralContactName",
        "CentralContactRole",
        "CentralContactPhone",
        "CentralContactEMail",
    ],
    "FlowGroups": [
        "NCTId",
        "FlowGroupId",
        "FlowGroupTitle",
        "FlowGroupDescription",
    ],
    "BaselineGroups": [
        "NCTId",
        "BaselineGroupId",
        "BaselineGroupTitle",
        "BaselineGroupDescription",
    ],
    "EventGroups": [
        "NCTId",
        "EventGroupId",
        "EventGroupTitle",
        "EventGroupDescription",
        "EventGroupDeathsNumAffected",
        "EventGroupDeathsNumAtRisk",
        "EventGroupSeriousNumAffected",
        "EventGroupSeriousNumAtRisk",
        "EventGroupOtherNumAffected",
        "EventGroupOtherNumAtRisk",
    ],
    "SeeAlsoLinks": [
        "NCTId",
        "SeeAlsoLinkLabel",
        "SeeAlsoLinkURL",
    ],
    "LargeDocs": [
        "NCTId",
        "LargeDocTypeAbbrev",
        "LargeDocHasProtocol",
        "LargeDocHasSAP",
        "LargeDocHasICF",
        "LargeDocLabel",
        "LargeDocDate",
        "LargeDocUploadDate",
        "LargeDocFilename",
        "LargeDocSize",
    ],
    "UnpostedEvents": [
        "NCTId",
        "UnpostedEventType",
        "UnpostedEventDate",
    ],
    "SubmissionInfos": [
        "NCTId",
        "SubmissionReleaseDate",
        "SubmissionResetDate",
    ],
    "AvailIPDs": [
        "NCTId",
        "AvailIPDId",
        "AvailIPDType",
        "AvailIPDURL",
        "AvailIPDComment",
    ],
    "FlowPeriods": [
        "NCTId",
        "FlowPeriodTitle",
    ],
    "FlowMilestones": [
        "FlowPeriodsId",
        "FlowMilestoneType",
    ],
    "FlowAchievements": [
        "FlowMilestonesId",
        "FlowAchievementGroupId",
        "FlowAchievementNumSubjects",
    ],
    "BaselineDenoms": ["ID", "NCTId", "BaselineDenomUnits"],
    "BaselineDenomCounts": [
        "BaselineDenomsId",
        "BaselineDenomCountGroupId",
        "BaselineDenomCountValue",
    ],
    "BaselineMeasures": [
        "NCTId",
        "BaselineMeasureTitle",
        "BaselineMeasureParamType",
        "BaselineMeasureUnitOfMeasure",
    ],
    "BaselineClasses": [
        "BaselineMeasureId",
    ],
    "BaselineCategories": [
        "BaselineClassId",
        "BaselineCategoryTitle",
    ],
    "BaselineMeasurements": [
        "BaselineCategoryId",
    ],
    "OutcomeMeasures": [
        "NCTId",
        "OutcomeMeasureType",
        "OutcomeMeasureTitle",
        "OutcomeMeasureDescription",
        "OutcomeMeasuresPopulationDescription",
        "OutcomeMeasuresReportingStatus",
        "OutcomeMeasuresParamType",
        "OutcomeMeasuresDispersionType",
        "OutcomeMeasuresUnitOfMeasure",
        "OutcomeMeasuresTimeFrame",
    ],
    "OutcomeGroups": [
        "OutcomeMeasureId",
        "OutcomeGroupId",
        "OutcomeGroupTitle",
        "OutcomeGroupDescription",
    ],
    "OutcomeDenoms": [
        "OutcomeMeasureId",
        "OutcomeDenomUnits",
    ],
    "OutcomeDenomCounts": [
        "OutcomeDenomId",
        "OutcomeDenomUnits",
    ],
    "OutcomeClasses": [
        "OutcomeMeasureId",
    ],
    "OutcomeCategories": [
        "OutcomeClassId",
    ],
    "OutcomeMeasurements": [
        "OutcomeCategoryId",
        "OutcomeMeasurementGroupId",
        "OutcomeMeasurementValue",
        "OutcomeMeasurementLowerLimit",
        "OutcomeMeasurementUpperLimit",
    ],
    "OtherEvents": [
        "NCTId",
        "OtherEventTerm",
        "OtherEventOrganSystem",
        "OtherEventAssessmentType",
    ],
    "OtherEventStats": [
        "OtherEventsId",
        "OtherEventStatsGroupId",
        "OtherEventStatsNumEvents",
        "OtherEventStatsNumAffected",
        "OtherEventStatsNumAtRisk",
    ],
    "SeriousEvents": [
        "NCTId",
        "SeriousEventTerm",
        "SeriousEventOrganSystem",
        "SeriousEventSourceVocabulary",
        "SeriousEventAssessmentType",
    ],
    "SeriousEventStats": [
        "SeriousEventsId",
        "SeriousEventStatsGroupId",
        "SeriousEventStatsNumAffected",
        "SeriousEventStatsNumAtRisk",
    ],
}
