import json

from litreview.studies import Studies

JSON_TO_TABLE = {
    "protocolSection.identificationModule.secondaryIdInfos": "SecondaryIdInfos",
    "protocolSection.sponsorCollaboratorsModule.collaborators": "Collaborators",
    "Condition": "Condition",
    "Keyword": "Keyword",
    "Phase": "Phase",
    "protocolSection.armsInterventionsModule.armGroups": "ArmGroups",
    "protocolSection.armsInterventionsModule.interventions": "Interventions",
    "protocolSection.outcomesModule.primaryOutcomes": "PrimaryOutcomes",
    "protocolSection.outcomesModule.secondaryOutcomes": "SecondaryOutcomes",
    "protocolSection.contactsLocationsModule.overallOfficials": "OverallOfficials",
    "protocolSection.contactsLocationsModule.locations": "Locations",
    "protocolSection.referencesModule.references": "StudyReferences",
    "derivedSection.conditionBrowseModule.meshes": "ConditionMeshes",
    "derivedSection.interventionBrowseModule.meshes": "InterventionMeshes",
    "derivedSection.conditionBrowseModule.ancestors": "ConditionAncestors",
    "derivedSection.interventionBrowseModule.ancestors": "InterventionAncestors",
    "derivedSection.conditionBrowseModule.browseLeaves": "ConditionBrowseLeaves",
    "derivedSection.interventionBrowseModule.browseLeaves": "InterventionBrowseLeaves",
    "derivedSection.conditionBrowseModule.browseBranches": "ConditionBrowseBranches",
    "derivedSection.interventionBrowseModule.browseBranches": "InterventionBrowseBranches",
}

STUDY_TABLE = [
    "NCTId",
    "OrgStudyId",
    "OrgFullName",
    "OrgClass",
    "BriefTitle",
    "OfficialTitle",
    "StatusVerifiedDate",
    "OverallStatus",
    "HasExpandedAccess",
    "StartDate",
    "PrimaryCompletionDate",
    "PrimaryCompletionDateType",
    "CompletionDate",
    "CompletionDateType",
    "StudyFirstSubmitDate",
    "StudyFirstSubmitQCDate",
    "StudyFirstPostDate",
    "StudyFirstPostDateType",
    "LastUpdateSubmitDate",
    "LastUpdatePostDate",
    "LastUpdatePostDateType",
    "ResponsiblePartyType",
    "LeadSponsorName",
    "LeadSponsorClass",
    "BriefSummary",
    "DetailedDescription",
    "StudyType",
    "DesignAllocation",
    "DesignPrimaryPurpose",
    "DesignMasking",
    "EnrollmentCount",
    "EnrollmentType",
    "EligibilityCriteria",
    "HealthyVolunteers",
    "Sex",
    "MinimumAge",
    "MaximumAge",
    "VersionHolder",
    "HasResults",
    "OversightHasDMC",
    "IsFDARegulatedDrug",
    "IsFDARegulatedDevice",
    "IPDSharing",
    "Condition",
    "Keyword",
    "Phase",
    "StdAge",
]

studies = Studies(500)
studies.get_studies()
